### ISSUE TITLE
Emergency Shuttle should be a plane, and CentCom should be a military base

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [frigid14/frigid-old#57]
- [x] ~~Make the E.S a plane than a shuttle~~ #66
- [x] ~~Make hyperspace parallax nukie parallax so it looks like you're flying across the Earth or something~~ #65 
- [x] ~~Make CentCom a military base~~ #66
